# Generated by Django 3.2.24 on 2024-03-27 19:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_post_category'),
        ('favourites', '0002_alter_favourite_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('post', 'owner')},
        ),
    ]
