# Generated by Django 3.2.24 on 2024-03-14 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_notifications_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='category',
            field=models.CharField(choices=[('follow', 'Follow'), ('comment', 'Comment')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
