# Generated by Django 3.2.24 on 2024-03-15 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_auto_20240314_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='category',
            field=models.CharField(choices=[('follow', 'Follow'), ('comment', 'Comment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='object_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
