# Generated by Django 3.2.24 on 2024-03-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20240315_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='recipient',
            new_name='owner',
        ),
    ]
